FROM debian

RUN apt update \
&& apt install python python-pip cron -y \
&& pip install scrapy service_identity mako --force --upgrade

RUN useradd spider -d /home/spider
RUN mkdir /home/spider && chown spider /home/spider && gpasswd -a spider root && chmod 4777 /var/run && chmod 4777 /var/log && chmod 4755 /usr/sbin/cron

USER spider
#RUN echo "spider:spider" | chpasswd

ADD spider /home/spider
WORKDIR /home/spider

CMD ["/home/spider/schedule.sh"]